import Head from "next/head";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.css";

export const metadata = {
  title: "Chat with PDF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body>{children}</body>
    </html>
  );
}
